<a href="https://colab.research.google.com/github/debarnabdas007/Learning-Pytorch/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.10.0+cpu


## Introduction to Tensors

### Creating Tensors

In [58]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [59]:
scalar.ndim

0

In [60]:
# Get tensor back as PYTHON INT
scalar.item()

7

In [61]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [62]:
vector.ndim

1

In [63]:
vector.shape

torch.Size([2])

In [64]:
# MATRIX

MATRIX = torch.tensor(([7,8],
                       [9,10]))
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [65]:
MATRIX.ndim

2

In [66]:
MATRIX[0]

tensor([7, 8])

In [67]:
MATRIX[1]

tensor([ 9, 10])

In [68]:
MATRIX.shape

torch.Size([2, 2])

In [69]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [70]:
TENSOR.ndim

3

In [71]:
TENSOR.shape

torch.Size([1, 3, 3])

In [72]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [73]:
## Watch
TENSOR = torch.tensor([[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]])
TENSOR

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [74]:
TENSOR.ndim

2

In [75]:
TENSOR.shape

torch.Size([3, 3])

### Random Tensor

### Random Tensor

Why random tensors?

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

'Start with random numbers --> Look at data --> update random numbers --> look at data --> update random numbers'

In [76]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1554, 0.0442, 0.8598, 0.2330],
        [0.5781, 0.9525, 0.9957, 0.5285],
        [0.7191, 0.4449, 0.1878, 0.4875]])

In [77]:
random_tensor.ndim

2

In [78]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size= (224, 224, 3)) # Height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and ONEs

In [79]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [80]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [81]:
# Create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [82]:
ones.dtype

torch.float32

In [83]:
random_tensor.dtype

torch.float32

### Creating a range of tensors ad tensors-like

In [84]:
# use torch.range() instead use:- torch.arange()
##  a range of numbers
one_to_ten = torch.arange(start= 0,end= 11, step= 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
# Creating tensors like
## Sometimes you might want one tensor of a certain type with the same shape as another tensor

ten_zeroes = torch.zeros_like(input= one_to_ten) # will have same shape
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor dataypes is one of the 3 big error you'll run into with PyTorch & deep learning
1. Tensors not right datatype
2. Tensor not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=In%20computer%20science%2C%20the%20precision,used%20to%20express%20a%20value.

| Type            | Meaning         | Use             |
| --------------- | --------------- | --------------- |
| `torch.float32` | default         | ✅ standard DL   |
| `torch.float16` | lower precision | 🚀 faster (GPU) |
| `torch.float64` | high precision  | 🧪 scientific   |


In [86]:
# Float 32 tensors
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # how detailed your measurement is (e.g. float32 or float16)
                               device = "cpu", # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients/track 'learning' with tensors opertations
float_32_tensor

tensor([3., 6., 9.])

In [87]:
float_32_tensor.dtype

torch.float32

In [88]:
# .type   used to conver dtype
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [89]:
p = float_16_tensor * float_32_tensor
p

tensor([ 9., 36., 81.])

In [90]:
p.dtype   #Observe:  16bits * 32 bits results 32 bits

## "Promote to higher precision"
# When two tensors have different dtypes: PyTorch automatically converts both to the safer (higher precision) type to avoid information loss

torch.float32

In [91]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype=torch.long)  #now manupulate this dtype and observe how product happens
int_32_tensor

tensor([3, 6, 9])

In [92]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (Tensor attributes)

1. Tensors not right datatype = to do get datatype from a tensor, can use `tensor.dtype`
2. Tensor not right shape = to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device = to get device from a tensor, can use `tensor.device`

In [93]:
# Craete a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1630, 0.1768, 0.3670, 0.4695],
        [0.5976, 0.9871, 0.6793, 0.8236],
        [0.0208, 0.9778, 0.3894, 0.0552]])

In [94]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of Tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")  # may use, some_tensor.size()
print(f"Device Tensor is on: {some_tensor.device}")

tensor([[0.1630, 0.1768, 0.3670, 0.4695],
        [0.5976, 0.9871, 0.6793, 0.8236],
        [0.0208, 0.9778, 0.3894, 0.0552]])
Datatype of Tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device Tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [95]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [96]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [97]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [98]:
## Try out PyTorch in-bult functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [99]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix Multiplication

Two main ways of performing multiplication in NN and DL

1. Element-wise multipplication
2. Matrix Multiplication (dot product)

More info on matrix-multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

Visulation: http://matrixmultiplication.xyz/




In [100]:
'''
a * b              # element-wise
torch.dot(a, b)   # dot product (1D only)
torch.matmul(a,b) # matrix multiplication / dot depending on shape




1️⃣ Element-wise multiplication

👉 Multiply position by position

a = [1,2,3]
b = [4,5,6]

result = [1*4, 2*5, 3*6]
       = [4,10,18]

👉 Output: vector



2️⃣ Dot product (special case)

👉 Multiply + sum everything

[1,2,3] · [4,5,6]
= 1*4 + 2*5 + 3*6
= 4 + 10 + 18
= 32

👉 Output: single number



3️⃣ Matrix multiplication

👉 Row × Column rule

Example:

A = [[1,2,3]]   # (1×3)
B = [[4],
     [5],
     [6]]       # (3×1)
= 1*4 + 2*5 + 3*6
= 32

👉 Output: matrix (1×1)



🔥 Key differences
| Operation    | How it works           | Output |
| ------------ | ---------------------- | ------ |
| Element-wise | position-wise multiply | vector |
| Dot product  | multiply + sum         | scalar |
| Matrix mult  | row × column           | matrix |

MAtrix Multiplicaiton = grid of dot products

'''

'\na * b              # element-wise\ntorch.dot(a, b)   # dot product (1D only)\ntorch.matmul(a,b) # matrix multiplication / dot depending on shape\n\n\n\n\n1️⃣ Element-wise multiplication\n\n👉 Multiply position by position\n\na = [1,2,3]\nb = [4,5,6]\n\nresult = [1*4, 2*5, 3*6]\n       = [4,10,18]\n\n👉 Output: vector\n\n\n\n2️⃣ Dot product (special case)\n\n👉 Multiply + sum everything\n\n[1,2,3] · [4,5,6]\n= 1*4 + 2*5 + 3*6\n= 4 + 10 + 18\n= 32\n\n👉 Output: single number\n\n\n\n3️⃣ Matrix multiplication\n\n👉 Row × Column rule\n\nExample:\n\nA = [[1,2,3]]   # (1×3)\nB = [[4],\n     [5],\n     [6]]       # (3×1)\n= 1*4 + 2*5 + 3*6\n= 32\n\n👉 Output: matrix (1×1)\n\n\n\n🔥 Key differences\n| Operation    | How it works           | Output |\n| ------------ | ---------------------- | ------ |\n| Element-wise | position-wise multiply | vector |\n| Dot product  | multiply + sum         | scalar |\n| Matrix mult  | row × column           | matrix |\n\nMAtrix Multiplicaiton = grid of dot produc

In [101]:
tensor.shape

torch.Size([3])

In [102]:
# Element wise Multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}" )

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [103]:
# Matrix Multiplication
p = torch.matmul(tensor, tensor)
p

tensor(14)

In [104]:
p.shape  #a 1D vector

torch.Size([])

In [105]:
# Matrix Mutliplication by Hand
1*1 + 2*2 + 3*3

14

In [106]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.5 ms, sys: 76 µs, total: 1.57 ms
Wall time: 3.44 ms


In [107]:
%%time
torch.matmul(tensor, tensor)    ## VECTORISATION

CPU times: user 75 µs, sys: 0 ns, total: 75 µs
Wall time: 79.9 µs


tensor(14)

### Two-main Rules to satisfy before matrix-multiplication:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. **outer dimensions** will be new shape of resulting matrix

In [108]:
# torch.matmul(torch.rand(3,2), torch.rand(3,2))
# won't work

In [109]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[1.0483, 1.7752],
        [0.7010, 0.8797]])

### One of the most common errors in deep learning: shape errors

In [110]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

# .matmul() is same as .mm() can use both
torch.matmul(tensor_A, tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [111]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes of a given tensor

In [112]:
tensor_B   # 3X2 shape

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [113]:
tensor_B.T   # 2X3 shape

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [114]:
##Now, the same information is rearranged !!

torch.matmul(tensor_A, tensor_B.T)   # 3X2 * 2X3 = 3X3

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Finding the min, max, sum, etc. (Tensor aggregation)

In [115]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [116]:
# Find the min
torch.min(x), x.min()   # CAN USE BOTH stuffs

(tensor(1), tensor(1))

In [117]:
# Find the mean
torch.mean(x)  ## error: Not right datatype

## torch's mean() function can't work with Long datatype.
## Input dtype must be either a floating point or complex dtype.



RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [118]:
torch.mean(x.type(torch.float32))

tensor(46.)

In [119]:
x.type(torch.float32).mean()

tensor(46.)

In [120]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))



```
# This is formatted as code
```

## Finding Positional min and max

In [121]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [122]:
# Find the position in tensor that has the minimum value with argmin()  --> returns index postion of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [123]:
# Find the exact index value
x[0]

tensor(1)

In [124]:
# Find the postion in tensor that has the maximum value with argmax()
x.argmax()  # --> return the index

tensor(9)

In [125]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping --> reshapes an input tensor to a defined shape
* View --> Return a view of an input tensor of certain shape but keep the same memory as the original tensor. But, Works only if memory layout allows.
* Stacking --> combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze --> removes all `1` dimensions from a tensor
* Unsqueeze --> add a `1` dimension to a target tensor
* Permute -->> Return a view of the input with the dimensions permuted (swapped) in a certain way

In [169]:
# create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape, x.dtype, x.ndim
print()

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 torch.float32,
 1)

In [170]:
# Add an extra dimension
x_reshaped = x.reshape(1,9) # no. of elements must match/valid as 5*2 = 10 and we have 10 total elements
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

### observe!
Initially, shape of x --> [9] with 1 square bracket  so 1D
but now shape of x_reshaped --> [1,9] with 2 square bracket so 2D

In [188]:
##  More examples of reshape
p = torch.arange(1., 11.)

print(f"Previosu tensor: {p}")
print(f"Previosu shape: {p.shape} ")
print(f"Previosu dimension: {p.ndim}")

# Remove extra dimensions from x_reshaped
p_reshaped = p.reshape(5, 2)  # no. of elements must match/valid as 5*2 = 10 and we have 10 total elements
print(f"\nNew tensor: {p_reshaped}")
print(f"New shape: {p_reshaped.shape}")
print(f"New dimesnsion: {p_reshaped.ndim}")

Previosu tensor: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previosu shape: torch.Size([10]) 
Previosu dimension: 1

New tensor: tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
New shape: torch.Size([5, 2])
New dimesnsion: 2


 Observe the shape change and Brackets here !

> intitally, [10] with 1 bracket so 1D but now [5, 2] with 2 brackets so 2D

In [175]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [176]:
# Changing z changes x ( because a view of tensor shares the same memory as the original input)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [177]:
# Stack tensors om top pf each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [178]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [179]:
# vstack-> dim=0 and hstack-> dim=1

In [186]:
# Squeeze
# torch.squeeze() = remove all single dimensions from a target tensor
print(f"Previosu tensor: {x_reshaped}")
print(f"Previosu shape: {x_reshaped.shape} ")
print(f"Previosu dimension: {x_reshaped.ndim}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")
print(f"New dimesnsion: {x_squeezed.ndim}")


## Obseerve: Dimension Change


Previosu tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previosu shape: torch.Size([1, 9]) 
Previosu dimension: 2

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])
New dimesnsion: 1


In [182]:
## Obseerve: Dimension Change

In [191]:
# Unsqueeze

## torch.unsqueeze() = adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")
print(f"Previous Dimension: {x_squeezed.ndim}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
print(f"New Dimension: {x_unsqueezed.ndim}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
Previous Dimension: 1

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])
New Dimension: 2


In [219]:
# Unsqueeze

## torch.unsqueeze() = adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")
print(f"Previous Dimension: {x_squeezed.ndim}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
print(f"New Dimension: {x_unsqueezed.ndim}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
Previous Dimension: 1

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])
New Dimension: 2


In [224]:
# Permute
## torch.permute(input, dims) = reaaranges the dimesnions of a target tensor in a specified order. returns view.

#* permute mostly used in Image stuffs
x_original = torch.rand(size= (224, 224, 3))  # H, W, #channels

#Permute the original tensor to reaarange the axis (or dim) order
x_permuted = x_original.permute (2, 0, 1) # shits axix 0->1, 1->2, 2->0

print(f"Previous Shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color channels, H, W]


Previous Shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [225]:
print(x_original[0,0,0])
x_original[0 , 0 , 0]= 78978
print(x_original[0,0,0])
print(x_permuted[0,0,0])

tensor(0.8588)
tensor(78978.)
tensor(78978.)


## Indexing ( selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy

In [227]:
# Create Tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape, x.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [241]:
# Let's index on our new Tensor
x[0], x[0].ndim    # Observe, we are inside the first bracket i.e. outer bracket and dimnesion is 2

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 2)

In [242]:
# index on the middle bracket (ndim = 1)
x[0][0], x[0, 0],             x[0, 0].ndim

# both are same thing !!

(tensor([1, 2, 3]), tensor([1, 2, 3]), 1)

In [243]:
# index on most inner bracket (ndim = 0)
x[0][0][0], x[0][0][1], x[0][0][2]

(tensor(1), tensor(2), tensor(3))

In [245]:
# Let's play
x[0][1]

tensor([4, 5, 6])

In [246]:
x[0][1][1]

tensor(5)

In [247]:
x[0][2][2]

tensor(9)

In [248]:
x[0][1][2]

tensor(6)

##### You can also use ":" to seelect "all" of a target dimension

In [253]:
## You can also use ":" to seelect "all" of a target dimension
## ':' = take ALL elements in that dimension
x[:, 0]

tensor([[1, 2, 3]])

In [250]:
x[0, 0]

tensor([1, 2, 3])

In [251]:
# Get all values of 0th and 1st dimesnions but only index  of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [254]:
# Get all values of the 0 dimension but only the 1 index value of 1st and wnd dimension
x[:, 1, 1]


# Observe!  give similar values as x[0][1][1] but a square bracket more.. so a scalar output vs a tensor output

tensor([5])

In [255]:
# Get index 0 of oth and 1st dimesnion and all calues of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [260]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [261]:
# Index on x to reutrn 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])
