<a href="https://colab.research.google.com/github/debarnabdas007/Learning-Pytorch/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Resource: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.10.0+cpu


## Introduction to Tensors

### Creating Tensors

In [3]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as PYTHON INT
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX

MATRIX = torch.tensor(([7,8],
                       [9,10]))
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [18]:
## Watch
TENSOR = torch.tensor([[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]])
TENSOR

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
TENSOR.ndim

2

In [20]:
TENSOR.shape

torch.Size([3, 3])

### Random Tensor

### Random Tensor

Why random tensors?

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

'Start with random numbers --> Look at data --> update random numbers --> look at data --> update random numbers'

In [21]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6143, 0.2721, 0.7566, 0.2671],
        [0.4447, 0.8006, 0.1357, 0.4660],
        [0.2986, 0.6370, 0.6447, 0.4992]])

In [22]:
random_tensor.ndim

2

In [23]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size= (224, 224, 3)) # Height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and ONEs

In [24]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
# Create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

In [28]:
random_tensor.dtype

torch.float32

### Creating a range of tensors ad tensors-like

In [29]:
# use torch.range() instead use:- torch.arange()
##  a range of numbers
one_to_ten = torch.arange(start= 0,end= 11, step= 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
# Creating tensors like
## Sometimes you might want one tensor of a certain type with the same shape as another tensor

ten_zeroes = torch.zeros_like(input= one_to_ten) # will have same shape
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor dataypes is one of the 3 big error you'll run into with PyTorch & deep learning
1. Tensors not right datatype
2. Tensor not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=In%20computer%20science%2C%20the%20precision,used%20to%20express%20a%20value.

| Type            | Meaning         | Use             |
| --------------- | --------------- | --------------- |
| `torch.float32` | default         | ✅ standard DL   |
| `torch.float16` | lower precision | 🚀 faster (GPU) |
| `torch.float64` | high precision  | 🧪 scientific   |


In [41]:
# Float 32 tensors
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # how detailed your measurement is (e.g. float32 or float16)
                               device = "cpu", # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients/track 'learning' with tensors opertations
float_32_tensor

tensor([3., 6., 9.])

In [42]:
float_32_tensor.dtype

torch.float32

In [43]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [48]:
p = float_16_tensor * float_32_tensor
p

tensor([ 9., 36., 81.])

In [49]:
p.dtype

torch.float32