<a href="https://colab.research.google.com/github/debarnabdas007/Learning-Pytorch/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Resource: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.10.0+cpu


## Introduction to Tensors

### Creating Tensors

In [3]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as PYTHON INT
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX

MATRIX = torch.tensor(([7,8],
                       [9,10]))
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [18]:
## Watch
TENSOR = torch.tensor([[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]])
TENSOR

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
TENSOR.ndim

2

In [20]:
TENSOR.shape

torch.Size([3, 3])

### Random Tensor

### Random Tensor

Why random tensors?

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

'Start with random numbers --> Look at data --> update random numbers --> look at data --> update random numbers'

In [21]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6143, 0.2721, 0.7566, 0.2671],
        [0.4447, 0.8006, 0.1357, 0.4660],
        [0.2986, 0.6370, 0.6447, 0.4992]])

In [22]:
random_tensor.ndim

2

In [23]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size= (224, 224, 3)) # Height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and ONEs

In [24]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
# Create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

In [28]:
random_tensor.dtype

torch.float32

### Creating a range of tensors ad tensors-like

In [29]:
# use torch.range() instead use:- torch.arange()
##  a range of numbers
one_to_ten = torch.arange(start= 0,end= 11, step= 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
# Creating tensors like
## Sometimes you might want one tensor of a certain type with the same shape as another tensor

ten_zeroes = torch.zeros_like(input= one_to_ten) # will have same shape
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor dataypes is one of the 3 big error you'll run into with PyTorch & deep learning
1. Tensors not right datatype
2. Tensor not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=In%20computer%20science%2C%20the%20precision,used%20to%20express%20a%20value.

| Type            | Meaning         | Use             |
| --------------- | --------------- | --------------- |
| `torch.float32` | default         | ✅ standard DL   |
| `torch.float16` | lower precision | 🚀 faster (GPU) |
| `torch.float64` | high precision  | 🧪 scientific   |


In [41]:
# Float 32 tensors
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # how detailed your measurement is (e.g. float32 or float16)
                               device = "cpu", # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients/track 'learning' with tensors opertations
float_32_tensor

tensor([3., 6., 9.])

In [42]:
float_32_tensor.dtype

torch.float32

In [43]:
# .type   used to conver dtype
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [48]:
p = float_16_tensor * float_32_tensor
p

tensor([ 9., 36., 81.])

In [49]:
p.dtype   #Observe:  16bits * 32 bits results 32 bits

## "Promote to higher precision"
# When two tensors have different dtypes: PyTorch automatically converts both to the safer (higher precision) type to avoid information loss

torch.float32

In [56]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype=torch.long)  #now manupulate this dtype and observe how product happens
int_32_tensor

tensor([3, 6, 9])

In [57]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (Tensor attributes)

1. Tensors not right datatype = to do get datatype from a tensor, can use `tensor.dtype`
2. Tensor not right shape = to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device = to get device from a tensor, can use `tensor.device`

In [58]:
# Craete a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[9.9681e-01, 8.4956e-01, 1.4859e-01, 5.9938e-04],
        [9.6609e-01, 7.5016e-01, 4.0631e-01, 5.6533e-01],
        [8.7143e-01, 2.7604e-01, 7.1958e-01, 1.2572e-01]])

In [59]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of Tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")  # may use, some_tensor.size()
print(f"Device Tensor is on: {some_tensor.device}")

tensor([[9.9681e-01, 8.4956e-01, 1.4859e-01, 5.9938e-04],
        [9.6609e-01, 7.5016e-01, 4.0631e-01, 5.6533e-01],
        [8.7143e-01, 2.7604e-01, 7.1958e-01, 1.2572e-01]])
Datatype of Tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device Tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [63]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [64]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [65]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [68]:
## Try out PyTorch in-bult functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [69]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix Multiplication

Two main ways of performing multiplication in NN and DL

1. Element-wise multipplication
2. Matrix Multiplication (dot product)

More info on matrix-multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

Visulation: http://matrixmultiplication.xyz/




In [ ]:
'''
a * b              # element-wise
torch.dot(a, b)   # dot product (1D only)
torch.matmul(a,b) # matrix multiplication / dot depending on shape




1️⃣ Element-wise multiplication

👉 Multiply position by position

a = [1,2,3]
b = [4,5,6]

result = [1*4, 2*5, 3*6]
       = [4,10,18]

👉 Output: vector



2️⃣ Dot product (special case)

👉 Multiply + sum everything

[1,2,3] · [4,5,6]
= 1*4 + 2*5 + 3*6
= 4 + 10 + 18
= 32

👉 Output: single number



3️⃣ Matrix multiplication

👉 Row × Column rule

Example:

A = [[1,2,3]]   # (1×3)
B = [[4],
     [5],
     [6]]       # (3×1)
= 1*4 + 2*5 + 3*6
= 32

👉 Output: matrix (1×1)



🔥 Key differences
| Operation    | How it works           | Output |
| ------------ | ---------------------- | ------ |
| Element-wise | position-wise multiply | vector |
| Dot product  | multiply + sum         | scalar |
| Matrix mult  | row × column           | matrix |

MAtrix Multiplicaiton = grid of dot products

'''

In [86]:
tensor.shape

torch.Size([3])

In [74]:
# Element wise Multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}" )

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [88]:
# Matrix Multiplication
p = torch.matmul(tensor, tensor)
p

tensor(14)

In [79]:
p.shape  #a 1D vector

torch.Size([])

In [ ]:
# Matrix Mutliplication by Hand
1*1 + 2*2 + 3*3

In [90]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 3.62 ms, sys: 49 µs, total: 3.67 ms
Wall time: 11.5 ms


In [91]:
%%time
torch.matmul(tensor, tensor)    ## VECTORISATION

CPU times: user 529 µs, sys: 43 µs, total: 572 µs
Wall time: 442 µs


tensor(14)

### Two-main Rules to satisfy before matrix-multiplication:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. **outer dimensions** will be new shape of resulting matrix

In [ ]:
# torch.matmul(torch.rand(3,2), torch.rand(3,2))
# won't work

In [95]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.5775, 0.3839],
        [1.0222, 0.7664]])

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

# .matmul() is same as .mm() can use both
torch.matmul(tensor_A, tensor_B)


In [101]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes of a given tensor

In [102]:
tensor_B   # 3X2 shape

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [104]:
tensor_B.T   # 2X3 shape

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [105]:
##Now, the same information is rearranged !!

torch.matmul(tensor_A, tensor_B.T)   # 3X2 * 2X3 = 3X3

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Finding the min, max, sum, etc. (Tensor aggregation)

In [107]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [110]:
# Find the min
torch.min(x), x.min()   # CAN USE BOTH stuffs

(tensor(0), tensor(0))

In [ ]:
# Find the mean
torch.mean(x)  ## error: Not right datatype

## torch's mean() function can't work with Long datatype.
## Input dtype must be either a floating point or complex dtype.



In [114]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [116]:
x.type(torch.float32).mean()

tensor(45.)

In [117]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
### FInding Postions