<a href="https://colab.research.google.com/github/debarnabdas007/Learning-Pytorch/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.10.0+cpu


## Introduction to Tensors

### Creating Tensors

In [ ]:
# scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as PYTHON INT
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX

MATRIX = torch.tensor(([7,8],
                       [9,10]))
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
## Watch
TENSOR = torch.tensor([[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]])
TENSOR

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR.ndim

2

In [ ]:
TENSOR.shape

torch.Size([3, 3])

### Random Tensor

### Random Tensor

Why random tensors?

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

'Start with random numbers --> Look at data --> update random numbers --> look at data --> update random numbers'

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7443, 0.5821, 0.5478, 0.2310],
        [0.1529, 0.7647, 0.1540, 0.5527],
        [0.1129, 0.4674, 0.7719, 0.7948]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size= (224, 224, 3)) # Height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and ONEs

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range of tensors ad tensors-like

In [ ]:
# use torch.range() instead use:- torch.arange()
##  a range of numbers
one_to_ten = torch.arange(start= 0,end= 11, step= 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
## Sometimes you might want one tensor of a certain type with the same shape as another tensor

ten_zeroes = torch.zeros_like(input= one_to_ten) # will have same shape
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor dataypes is one of the 3 big error you'll run into with PyTorch & deep learning
1. Tensors not right datatype
2. Tensor not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=In%20computer%20science%2C%20the%20precision,used%20to%20express%20a%20value.

| Type            | Meaning         | Use             |
| --------------- | --------------- | --------------- |
| `torch.float32` | default         | ✅ standard DL   |
| `torch.float16` | lower precision | 🚀 faster (GPU) |
| `torch.float64` | high precision  | 🧪 scientific   |


In [ ]:
# Float 32 tensors
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # how detailed your measurement is (e.g. float32 or float16)
                               device = "cpu", # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients/track 'learning' with tensors opertations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# .type   used to conver dtype
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
p = float_16_tensor * float_32_tensor
p

tensor([ 9., 36., 81.])

In [ ]:
p.dtype   #Observe:  16bits * 32 bits results 32 bits

## "Promote to higher precision"
# When two tensors have different dtypes: PyTorch automatically converts both to the safer (higher precision) type to avoid information loss

torch.float32

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9],
                             dtype=torch.long)  #now manupulate this dtype and observe how product happens
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (Tensor attributes)

1. Tensors not right datatype = to do get datatype from a tensor, can use `tensor.dtype`
2. Tensor not right shape = to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device = to get device from a tensor, can use `tensor.device`

In [ ]:
# Craete a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.3356, 0.4494, 0.0016, 0.2538],
        [0.1439, 0.8364, 0.0951, 0.5321],
        [0.4643, 0.4282, 0.9542, 0.7070]])

In [ ]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of Tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")  # may use, some_tensor.size()
print(f"Device Tensor is on: {some_tensor.device}")

tensor([[0.3356, 0.4494, 0.0016, 0.2538],
        [0.1439, 0.8364, 0.0951, 0.5321],
        [0.4643, 0.4282, 0.9542, 0.7070]])
Datatype of Tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device Tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
## Try out PyTorch in-bult functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix Multiplication

Two main ways of performing multiplication in NN and DL

1. Element-wise multipplication
2. Matrix Multiplication (dot product)

More info on matrix-multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

Visulation: http://matrixmultiplication.xyz/




In [ ]:
'''
a * b              # element-wise
torch.dot(a, b)   # dot product (1D only)
torch.matmul(a,b) # matrix multiplication / dot depending on shape




1️⃣ Element-wise multiplication

👉 Multiply position by position

a = [1,2,3]
b = [4,5,6]

result = [1*4, 2*5, 3*6]
       = [4,10,18]

👉 Output: vector



2️⃣ Dot product (special case)

👉 Multiply + sum everything

[1,2,3] · [4,5,6]
= 1*4 + 2*5 + 3*6
= 4 + 10 + 18
= 32

👉 Output: single number



3️⃣ Matrix multiplication

👉 Row × Column rule

Example:

A = [[1,2,3]]   # (1×3)
B = [[4],
     [5],
     [6]]       # (3×1)
= 1*4 + 2*5 + 3*6
= 32

👉 Output: matrix (1×1)



🔥 Key differences
| Operation    | How it works           | Output |
| ------------ | ---------------------- | ------ |
| Element-wise | position-wise multiply | vector |
| Dot product  | multiply + sum         | scalar |
| Matrix mult  | row × column           | matrix |

MAtrix Multiplicaiton = grid of dot products

'''

'\na * b              # element-wise\ntorch.dot(a, b)   # dot product (1D only)\ntorch.matmul(a,b) # matrix multiplication / dot depending on shape\n\n\n\n\n1️⃣ Element-wise multiplication\n\n👉 Multiply position by position\n\na = [1,2,3]\nb = [4,5,6]\n\nresult = [1*4, 2*5, 3*6]\n       = [4,10,18]\n\n👉 Output: vector\n\n\n\n2️⃣ Dot product (special case)\n\n👉 Multiply + sum everything\n\n[1,2,3] · [4,5,6]\n= 1*4 + 2*5 + 3*6\n= 4 + 10 + 18\n= 32\n\n👉 Output: single number\n\n\n\n3️⃣ Matrix multiplication\n\n👉 Row × Column rule\n\nExample:\n\nA = [[1,2,3]]   # (1×3)\nB = [[4],\n     [5],\n     [6]]       # (3×1)\n= 1*4 + 2*5 + 3*6\n= 32\n\n👉 Output: matrix (1×1)\n\n\n\n🔥 Key differences\n| Operation    | How it works           | Output |\n| ------------ | ---------------------- | ------ |\n| Element-wise | position-wise multiply | vector |\n| Dot product  | multiply + sum         | scalar |\n| Matrix mult  | row × column           | matrix |\n\nMAtrix Multiplicaiton = grid of dot produc

In [ ]:
tensor.shape

torch.Size([3])

In [ ]:
# Element wise Multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}" )

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication
p = torch.matmul(tensor, tensor)
p

tensor(14)

In [ ]:
p.shape  #a 1D vector

torch.Size([])

In [ ]:
# Matrix Mutliplication by Hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.17 ms, sys: 21 µs, total: 1.2 ms
Wall time: 1.87 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)    ## VECTORISATION

CPU times: user 0 ns, sys: 230 µs, total: 230 µs
Wall time: 202 µs


tensor(14)

### Two-main Rules to satisfy before matrix-multiplication:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. **outer dimensions** will be new shape of resulting matrix

In [ ]:
# torch.matmul(torch.rand(3,2), torch.rand(3,2))
# won't work

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.8298, 0.1845],
        [0.7763, 0.2047]])

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

# .matmul() is same as .mm() can use both
torch.matmul(tensor_A, tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes of a given tensor

In [ ]:
tensor_B   # 3X2 shape

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [ ]:
tensor_B.T   # 2X3 shape

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [ ]:
##Now, the same information is rearranged !!

torch.matmul(tensor_A, tensor_B.T)   # 3X2 * 2X3 = 3X3

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

## Finding the min, max, sum, etc. (Tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the min
torch.min(x), x.min()   # CAN USE BOTH stuffs

(tensor(1), tensor(1))

In [ ]:
# Find the mean
torch.mean(x)  ## error: Not right datatype

## torch's mean() function can't work with Long datatype.
## Input dtype must be either a floating point or complex dtype.



RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float32))

tensor(46.)

In [ ]:
x.type(torch.float32).mean()

tensor(46.)

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))



```
# This is formatted as code
```

## Finding Positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minimum value with argmin()  --> returns index postion of target tensor where minimum value occurs
x.argmin()

tensor(0)

In [ ]:
# Find the exact index value
x[0]

tensor(1)

In [ ]:
# Find the postion in tensor that has the maximum value with argmax()
x.argmax()  # --> return the index

tensor(9)

In [ ]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping --> reshapes an input tensor to a defined shape
* View --> Return a view of an input tensor of certain shape but keep the same memory as the original tensor. But, Works only if memory layout allows.
* Stacking --> combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze --> removes all `1` dimensions from a tensor
* Unsqueeze --> add a `1` dimension to a target tensor
* Permute -->> Return a view of the input with the dimensions permuted (swapped) in a certain way

In [ ]:
# create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape, x.dtype, x.ndim
print()

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1,9) # no. of elements must match/valid as 5*2 = 10 and we have 10 total elements
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

### observe!
Initially, shape of x --> [9] with 1 square bracket  so 1D
but now shape of x_reshaped --> [1,9] with 2 square bracket so 2D

In [ ]:
##  More examples of reshape
p = torch.arange(1., 11.)

print(f"Previosu tensor: {p}")
print(f"Previosu shape: {p.shape} ")
print(f"Previosu dimension: {p.ndim}")

# Remove extra dimensions from x_reshaped
p_reshaped = p.reshape(5, 2)  # no. of elements must match/valid as 5*2 = 10 and we have 10 total elements
print(f"\nNew tensor: {p_reshaped}")
print(f"New shape: {p_reshaped.shape}")
print(f"New dimesnsion: {p_reshaped.ndim}")

Previosu tensor: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previosu shape: torch.Size([10]) 
Previosu dimension: 1

New tensor: tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
New shape: torch.Size([5, 2])
New dimesnsion: 2


 Observe the shape change and Brackets here !

> intitally, [10] with 1 bracket so 1D but now [5, 2] with 2 brackets so 2D

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x ( because a view of tensor shares the same memory as the original input)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors om top pf each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# vstack-> dim=0 and hstack-> dim=1

In [ ]:
# Squeeze
# torch.squeeze() = remove all single dimensions from a target tensor
print(f"Previosu tensor: {x_reshaped}")
print(f"Previosu shape: {x_reshaped.shape} ")
print(f"Previosu dimension: {x_reshaped.ndim}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")
print(f"New dimesnsion: {x_squeezed.ndim}")


## Obseerve: Dimension Change


Previosu tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previosu shape: torch.Size([1, 9]) 
Previosu dimension: 2

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])
New dimesnsion: 1


In [ ]:
## Obseerve: Dimension Change

In [ ]:
# Unsqueeze

## torch.unsqueeze() = adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")
print(f"Previous Dimension: {x_squeezed.ndim}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
print(f"New Dimension: {x_unsqueezed.ndim}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
Previous Dimension: 1

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])
New Dimension: 2


In [ ]:
# Unsqueeze

## torch.unsqueeze() = adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")
print(f"Previous Dimension: {x_squeezed.ndim}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
print(f"New Dimension: {x_unsqueezed.ndim}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
Previous Dimension: 1

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])
New Dimension: 2


In [ ]:
# Permute
## torch.permute(input, dims) = reaaranges the dimesnions of a target tensor in a specified order. returns view.

#* permute mostly used in Image stuffs
x_original = torch.rand(size= (224, 224, 3))  # H, W, #channels

#Permute the original tensor to reaarange the axis (or dim) order
x_permuted = x_original.permute (2, 0, 1) # shits axix 0->1, 1->2, 2->0

print(f"Previous Shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color channels, H, W]


Previous Shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
print(x_original[0,0,0])
x_original[0 , 0 , 0]= 78978
print(x_original[0,0,0])
print(x_permuted[0,0,0])

tensor(0.1300)
tensor(78978.)
tensor(78978.)


## Indexing ( selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy

In [ ]:
# Create Tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape, x.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [ ]:
# Let's index on our new Tensor
x[0], x[0].ndim    # Observe, we are inside the first bracket i.e. outer bracket and dimnesion is 2

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 2)

In [ ]:
# index on the middle bracket (ndim = 1)
x[0][0], x[0, 0],             x[0, 0].ndim

# both are same thing !!

(tensor([1, 2, 3]), tensor([1, 2, 3]), 1)

In [ ]:
# index on most inner bracket (ndim = 0)
x[0][0][0], x[0][0][1], x[0][0][2]

(tensor(1), tensor(2), tensor(3))

In [ ]:
# Let's play
x[0][1]

tensor([4, 5, 6])

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[0][1][2]

tensor(6)

##### You can also use ":" to seelect "all" of a target dimension

In [ ]:
## You can also use ":" to seelect "all" of a target dimension
## ':' = take ALL elements in that dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[0, 0]

tensor([1, 2, 3])

In [ ]:
# Get all values of 0th and 1st dimesnions but only index  of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and wnd dimension
x[:, 1, 1]


# Observe!  give similar values as x[0][1][1] but a square bracket more.. so a scalar output vs a tensor output

tensor([5])

In [ ]:
# Get index 0 of oth and 1st dimesnion and all calues of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# Index on x to reutrn 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


## Pytorch tensors and Numy

Numpy is a popular scientific Python numerical library

And because of this, PyTorch has functionality to interact to it.

* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [ ]:
# Numpy array to Tensor

import torch
import numpy as np

array = np.arange(1.0, 8.0)   # np.arange !!
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise !!
array, array.dtype, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
torch.arange(1., 8.0).dtype  ## float32 is default PyTorch datatype

torch.float32

In [ ]:
# Default Numpy datatype is float64 and thus PyTorch reflects that specific dataype when we covert numpy to pytorch
# Whereas, PyTorch default datatype is float32 !!

In [ ]:
# if we change the value of array, what will this do to `tensor` ?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# so tensor does not change if we change the original array

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
## Observe datatype !
numpy_tensor.dtype

dtype('float32')

In [ ]:
# Change the tensor, what happens to `numpy_tensor` ?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
### So they don't share Memory !!

## Reporducibility (trying to take random out of random)

In short how a NN learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in NN and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
torch.rand(3, 3)

tensor([[0.0112, 0.3236, 0.9442],
        [0.4175, 0.1082, 0.7595],
        [0.1092, 0.4479, 0.1553]])

In [ ]:
import torch

#create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8882, 0.7643, 0.5089, 0.1831],
        [0.6186, 0.7271, 0.0793, 0.0995],
        [0.1724, 0.1464, 0.0046, 0.9225]])
tensor([[0.6456, 0.2098, 0.3180, 0.4302],
        [0.3917, 0.0523, 0.3200, 0.6031],
        [0.7615, 0.5265, 0.2388, 0.0737]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


#### What is a “seed”?

* Seed = starting point for randomness

Think:

* Random numbers are not truly random
* They follow a hidden pattern
* Seed decides where to start in that pattern

In [ ]:
# Let's make some random but reproducible tensors
import torch

#set the random seed
RANDOM_SEED = 42    # Means: Start randomness from point 42

torch.manual_seed(RANDOM_SEED)        ##   !!
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)        ##   !!
random_tensor_D = torch.rand(3, 4)

# Same seed -> same starting point
# Same operations -> same numbers


print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


#### What is **Reproducibility** ?

`Getting the same results again and again`

#### Why it matters in ML:
* Debugging
* Experiments
* Comparing models


#### Real-world analogy
Think:

* Random = shuffled cards
* Seed = fixed shuffle pattern

Same seed -> same shuffle every time

####  Golden rules
1. torch.rand() → random every time
2. torch.manual_seed(x) → fixes randomness
3. Same seed + same code → same output

#### One-line summary

Seed controls randomness → ensures reproducibility

#### Exra resources for Reproducibilty:

*  https://docs.pytorch.org/docs/stable/notes/randomness.html

* https://en.wikipedia.org/wiki/Random_seed

## Running Tensors and PyTorch objects in the GPUs (and making faster computations)

GPUs = faster computationon on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good)

### 1. Getting a GPU

1. Easiest - Use Google Collab for Free GPU (options to upgrade as well)
2. Use your own GPU = takes a little bit of setup and requires the investment of purchasing a GPU, there's a lots of options... see this post for options to get: https://timdettmers.com/category/deep-learning/
3. Use cloud computing - GCP, AWS, Azure(Mictrosoft), these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [ ]:
!nvidia-smi

Wed Apr  8 08:21:22 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   40C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [1]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU

In [2]:
# Setup Device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [9]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device="cpu")

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [10]:
# Move tensor to GPU ( if available )
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU


In [11]:
# if tensor is on GPU, can't transform it to Numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [12]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU then convert it to Numpy
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [13]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')